# ============================================
# AOSP Full Source Build Configuration
# Google Cloud Build
# ============================================

# Define build steps - each step runs in sequence
steps:

  # ========== STEP 1: Install Dependencies ==========
  - name: 'ubuntu:22.04'
    id: 'install-dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "STEP 1: Installing Dependencies..."
        echo "=========================================="
        
        # Update package manager
        apt-get update
        
        # Install all required packages for AOSP build
        apt-get install -y \
          git \
          repo \
          python3 \
          ccache \
          openjdk-11-jdk-headless \
          flex \
          bison \
          build-essential \
          zip \
          unzip \
          libssl-dev \
          curl \
          wget \
          imagemagick \
          git-core \
          gnupg \
          liblz4-tool \
          libncurses5-dev \
          libsdl1.2-dev \
          libwxgtk3.0-gtk3-dev \
          lzop \
          pngcrush \
          rsync \
          schedtool \
          squashfs-tools \
          xsltproc \
          yasm \
          zipalign \
          zlib1g-dev \
          dosfstools \
          e2fsprogs \
          fdisk \
          kpartx \
          mtools \
        
        # Configure git (required for repo sync)
        git config --global user.email "aswin14887@gmail.com"
        git config --global user.name "Aswin Vodapally"
        
        echo "✓ Dependencies installed successfully"

  # ========== STEP 2: Initialize AOSP Repository ==========
  - name: 'ubuntu:22.04'
    id: 'init-repo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "STEP 2: Initializing AOSP Repository..."
        echo "=========================================="
        
        # Create AOSP directory
        mkdir -p /workspace/aosp
        cd /workspace/aosp
        
        # Initialize repo with AOSP manifest
        # Change android-14.0.0_r1 to your desired branch:
        # - android-14.0.0_r1  (Android 14)
        # - android-13.0.0_r1  (Android 13)
        # - android-12.0.0_r1  (Android 12)
        repo init \
          -u https://android.googlesource.com/platform/manifest \
          -b android-15.0.0_r32 \
          --depth=1 \
          --no-clone-bundle

        curl -o .repo/local_manifests/manifest_brcm_rpi.xml \
          -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-15.0/manifest_brcm_rpi.xml --create-dirs
        
        curl -o .repo/local_manifests/remove_projects.xml \
          -L https://raw.githubusercontent.com/raspberry-vanilla/android_local_manifest/android-15.0/remove_projects.xml
        
        echo "✓ Repository initialized successfully"
    
    # Wait for previous step to complete
    waitFor: ['install-dependencies']

  # ========== STEP 3: Sync AOSP Source Code ==========
  - name: 'ubuntu:22.04'
    id: 'sync-source'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "STEP 3: Syncing AOSP Source Code..."
        echo "This may take 30-60 minutes..."
        echo "=========================================="
        
        cd /workspace/aosp
        
        # Enable ccache (caches build files for faster rebuilds)
        export USE_CCACHE=1
        export CCACHE_DIR=/workspace/ccache
        mkdir -p $CCACHE_DIR
        
        # Sync all repositories in parallel
        # -j8 = 8 parallel download jobs
        # Adjust based on your network speed
        repo sync \
          -j8 \
          --no-clone-bundle \
          --no-tags \
          --force-sync
        
        echo "✓ Source code synced successfully"
    
    # This step depends on the init-repo step
    waitFor: ['init-repo']
    
    # Increase timeout (syncing takes time)
    timeout: '7200s'  # 2 hours

  # ========== STEP 4: Setup Build Environment ==========
  - name: 'ubuntu:22.04'
    id: 'setup-build-env'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "STEP 4: Setting up Build Environment..."
        echo "=========================================="
        
        cd /workspace/aosp
        
        # Source the build environment setup script
        # This loads all AOSP build variables
        source build/envsetup.sh
        
        
        lunch aosp_rpi5_car-bp1a-userdebug
        
        # Display build configuration
        echo ""
        echo "=========================================="
        echo "Build Configuration:"
        echo "=========================================="
        echo "Platform Version: $PLATFORM_VERSION"
        echo "Target Product: $TARGET_PRODUCT"
        echo "Build Variant: $TARGET_BUILD_VARIANT"
        echo "=========================================="
        
        echo "✓ Build environment configured successfully"
    
    waitFor: ['sync-source']

  # ========== STEP 5: Build AOSP ==========
  - name: 'ubuntu:22.04'
    id: 'build-aosp'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=========================================="
        echo "STEP 5: Building AOSP..."
        echo "This will take 2-6 hours..."
        echo "=========================================="
        
        cd /workspace/aosp
        
        # Setup environment again (new bash session)
        source build/envsetup.sh
        lunch aosp_rpi5_car-bp1a-userdebug
        
        # Enable ccache and build
        export USE_CCACHE=1
        export CCACHE_DIR=/workspace/ccache
        
        # Build AOSP with parallel jobs
        # -j4 = 4 parallel jobs (conservative for cloud)
        # Increase to -j8 if you have more resources
        make bootimage systemimage vendorimage -j4 2>&1 | tee /workspace/build.log
        
        echo ""
        echo "=========================================="
        echo "✓ Build completed successfully!"
        echo "=========================================="
    
    waitFor: ['setup-build-env']
    
    # Allow enough time for full build
    timeout: '14400s'  # 4 hours
    
    # Set environment variables for this step
    env:
      - 'USE_CCACHE=1'
      - 'CCACHE_DIR=/workspace/ccache'

  # ========== STEP 6: Upload Build Artifacts ==========
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-artifacts'
    args:
      - '-m'      # multi-threaded
      - 'cp'      # copy
      - '-r'      # recursive
      - '/workspace/aosp/out/target/product/'
      - 'gs://dulcet-analyst-484512-n8/build-${BUILD_ID}/'
    
    waitFor: ['build-aosp']

  # ========== STEP 7: Upload Build Log ==========
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-log'
    args:
      - 'cp'
      - '/workspace/build.log'
      - 'gs://dulcet-analyst-484512-n8/build-${BUILD_ID}/build.log'
    
    waitFor: ['build-aosp']

# ============================================
# Build Options & Configuration
# ============================================

options:
  # Machine type: determines CPU cores and RAM
  # Options: N1_HIGHCPU_4, N1_HIGHCPU_8, N1_HIGHCPU_32, N1_HIGHCPU_96
  # Recommended: N1_HIGHCPU_8 (8 cores, 7.2GB RAM)
  machineType: 'N1_HIGHCPU_8'
  
  # Logging configuration
  logging: CLOUD_LOGGING_ONLY

# Maximum build time (must be less than 24 hours)
# Current: 6 hours (21600 seconds)
timeout: '21600s'

# ============================================
# Substitution Variables
# ============================================

substitutions:
  # Can be overridden when submitting build
  _BUILD_VARIANT: 'userdebug'
  _ANDROID_BRANCH: 'android-15.0.0_r32'
